/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DefenseObservable.DefenseObservable;
import DefenseObserver.DefenseObserver;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Sahan Chamara
 */
public class HelicopterView extends javax.swing.JFrame implements DefenseObserver {

    private boolean isSelected;   
    private DefenseObservable observable;

    /**
     * Creates new form HelicopterView
     *
     *
     * @param observable     
     * @param
     */
    public HelicopterView(DefenseObservable observable){
        this.observable=observable;
        
        initComponents();
        setTopRightPosition();
        btnMissile.setEnabled(false);
        btnShoot1.setEnabled(false);
        btnLaser.setEnabled(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAreaHelicopter = new javax.swing.JLabel();
        btnMissile = new javax.swing.JButton();
        btnShoot1 = new javax.swing.JButton();
        btnLaser = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaHelicopter = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        txtFieldHeli = new javax.swing.JTextField();
        btnSendHelicopter = new javax.swing.JButton();
        chkPositionHeli = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(14, 18, 21));
        jLabel1.setText("Helicopter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 0, 160, 50);

        lblAreaHelicopter.setBackground(new java.awt.Color(0, 0, 0));
        lblAreaHelicopter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAreaHelicopter.setText("Area Not Cleared");
        lblAreaHelicopter.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblAreaHelicopterInputMethodTextChanged(evt);
            }
        });
        getContentPane().add(lblAreaHelicopter);
        lblAreaHelicopter.setBounds(40, 60, 117, 20);

        btnMissile.setBackground(new java.awt.Color(38, 53, 57));
        btnMissile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMissile.setForeground(new java.awt.Color(255, 255, 255));
        btnMissile.setText("Missile Operation");
        btnMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissileActionPerformed(evt);
            }
        });
        getContentPane().add(btnMissile);
        btnMissile.setBounds(80, 180, 150, 30);

        btnShoot1.setBackground(new java.awt.Color(38, 53, 57));
        btnShoot1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnShoot1.setForeground(new java.awt.Color(255, 255, 255));
        btnShoot1.setText("Shoot");
        btnShoot1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnShoot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShoot1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnShoot1);
        btnShoot1.setBounds(170, 220, 90, 30);

        btnLaser.setBackground(new java.awt.Color(38, 53, 57));
        btnLaser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLaser.setForeground(new java.awt.Color(255, 255, 255));
        btnLaser.setText("Laser Operation");
        btnLaser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaserActionPerformed(evt);
            }
        });
        getContentPane().add(btnLaser);
        btnLaser.setBounds(10, 220, 130, 30);

        jSlider1.setBackground(new java.awt.Color(255, 255, 255));
        jSlider1.setMajorTickSpacing(20);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        getContentPane().add(jSlider1);
        jSlider1.setBounds(500, 110, 60, 200);

        txtAreaHelicopter.setBackground(new java.awt.Color(171, 179, 158));
        txtAreaHelicopter.setColumns(20);
        txtAreaHelicopter.setRows(5);
        jScrollPane1.setViewportView(txtAreaHelicopter);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 90, 230, 70);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Soldire Count");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 50, 75, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount Count");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 80, 81, 16);

        jSpinner1.setOpaque(true);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(520, 50, 55, 22);
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(520, 80, 55, 22);

        txtFieldHeli.setBackground(new java.awt.Color(109, 102, 86));
        txtFieldHeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldHeliActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldHeli);
        txtFieldHeli.setBounds(30, 330, 414, 22);

        btnSendHelicopter.setBackground(new java.awt.Color(38, 53, 57));
        btnSendHelicopter.setForeground(new java.awt.Color(255, 255, 255));
        btnSendHelicopter.setText("Send");
        btnSendHelicopter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendHelicopterActionPerformed(evt);
            }
        });
        getContentPane().add(btnSendHelicopter);
        btnSendHelicopter.setBounds(470, 330, 101, 22);

        chkPositionHeli.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        chkPositionHeli.setText("Position");
        chkPositionHeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPositionHeliActionPerformed(evt);
            }
        });
        getContentPane().add(chkPositionHeli);
        chkPositionHeli.setBounds(200, 50, 74, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Background Videos/heli resize 2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 610, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void defense(int position) {
        if (position > 20 && isSelected) {
            btnShoot1.setEnabled(true);
        } else {
            btnShoot1.setEnabled(false);
        }
        if (position > 40 && isSelected) {
            btnMissile.setEnabled(true);
        } else {
            btnMissile.setEnabled(false);
        }
        if (position > 60 && isSelected) {
            btnLaser.setEnabled(true);
        } else {
            btnLaser.setEnabled(false);
        }
    }

    @Override
    public void setAreaText(boolean isSelected) {
        if (isSelected) {
            lblAreaHelicopter.setText("Area Cleared");
        } else {
            lblAreaHelicopter.setText("Area Not Cleared");
        }
    }

    @Override
    public void setSendMsg(String msg) {
        txtAreaHelicopter.setText(msg);
    }

//    @Override
//    public void getMsg(){
//        String enterMsg = txtFieldHeli.getText();
//        MainControllerView mView = new MainControllerView();
//        mView.setMsg(enterMsg);
//    }

    private void btnMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissileActionPerformed

    }//GEN-LAST:event_btnMissileActionPerformed

    private void btnShoot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShoot1ActionPerformed

    }//GEN-LAST:event_btnShoot1ActionPerformed

    private void btnLaserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaserActionPerformed

    }//GEN-LAST:event_btnLaserActionPerformed

    private void chkPositionHeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPositionHeliActionPerformed
        isSelected = chkPositionHeli.isSelected();

    }//GEN-LAST:event_chkPositionHeliActionPerformed

    private void lblAreaHelicopterInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblAreaHelicopterInputMethodTextChanged
        // TODO add your handling code here:


    }//GEN-LAST:event_lblAreaHelicopterInputMethodTextChanged

    private void btnSendHelicopterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendHelicopterActionPerformed
        observable.militaryVehicleSendMsg("Helicopter : "+txtFieldHeli.getText());        
          
    }//GEN-LAST:event_btnSendHelicopterActionPerformed

    private void txtFieldHeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldHeliActionPerformed
//        mainView.setComingMsg(txtFieldHeli.getText());
    }//GEN-LAST:event_txtFieldHeliActionPerformed

    private void setTopRightPosition() {
    // Get the screen dimensions
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    
    // Get the size of the JFrame
    int frameWidth = this.getWidth();
    int frameHeight = this.getHeight();

    // Calculate the top-right position
    int x = screenSize.width - frameWidth;
    int y = 0; // Top edge

    // Set the JFrame's location
    this.setLocation(x, y);
}
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HelicopterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HelicopterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HelicopterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HelicopterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HelicopterView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaser;
    private javax.swing.JButton btnMissile;
    private javax.swing.JButton btnSendHelicopter;
    private javax.swing.JButton btnShoot1;
    private javax.swing.JCheckBox chkPositionHeli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel lblAreaHelicopter;
    private javax.swing.JTextArea txtAreaHelicopter;
    private javax.swing.JTextField txtFieldHeli;
    // End of variables declaration//GEN-END:variables

    
}
