/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DefenseObservable.DefenseObservable;
import MilitaryVehicleEnum.MilitaryVehicle;
import jaco.mp3.player.MP3Player;
import javax.sound.sampled.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.Timer;

/**
 *
 * @author Sahan Chamara
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(960, 540));
        setMinimumSize(new java.awt.Dimension(960, 540));
        setPreferredSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Background Videos/Title.gif"))); // NOI18N
        jLabel1.setText("Warface Legacy");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 158, 31), new java.awt.Color(242, 158, 31), new java.awt.Color(79, 85, 74), new java.awt.Color(79, 85, 74)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 420, 320, 60);

        btnStart.setBackground(new java.awt.Color(241, 157, 16));
        btnStart.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        btnStart.setForeground(new java.awt.Color(133, 92, 38));
        btnStart.setText("START");
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart);
        btnStart.setBounds(750, 20, 120, 40);

        btnQuit.setBackground(new java.awt.Color(241, 157, 16));
        btnQuit.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(133, 92, 38));
        btnQuit.setText("Quit");
        btnQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitMouseClicked(evt);
            }
        });
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuit);
        btnQuit.setBounds(750, 80, 120, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Background Videos/My Home GIF - Call of Duty_ Black Ops 6 Official Multiplayer Theme.gif"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-3, -4, 960, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

        new LoadingView().setVisible(true);
        MP3Player player = new MP3Player(new File("C:\\Users\\Sahan Chamara\\Music\\Defense System\\Main\\src\\GUI\\Background Videos\\Black ops cold war gearing up scene.mp3"));
        player.play();

        Timer timer = new Timer(25000, (ActionEvent e) -> {

            //            DefenseObservable ob = new DefenseObservable();
            //            new MainControllerView(ob).setVisible(true);
            //            MainControllerView mainView = new MainControllerView(ob);
            DefenseObservable ob = new DefenseObservable();
            
//            MainControllerView mainView = new MainControllerView(ob);
            MainControllerView instance = MainControllerView.getInstance();
            instance.observableInterfaceReference(ob);
            
//            ob.addDefense(new HelicopterView(mainView));
//            ob.addDefense(new TankView(mainView));
//            ob.addDefense(new SubmarineView(mainView));

              ob.addDefense(new HelicopterView(ob));
              ob.addDefense(new TankView(ob));
              ob.addDefense(new SubmarineView(ob));
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        new LoadingView().setVisible(true);
        MP3Player player = new MP3Player(new File("C:\\Users\\Sahan Chamara\\Music\\Defense System\\Main\\src\\GUI\\Background Videos\\sniper-rifle-firing-shot-1-39789.mp3"));
        player.play();
    }//GEN-LAST:event_btnStartMouseClicked

    private void btnQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitMouseClicked
        new LoadingView().setVisible(true);
        MP3Player player = new MP3Player(new File("C:\\Users\\Sahan Chamara\\Music\\Defense System\\Main\\src\\GUI\\Background Videos\\sniper-rifle-firing-shot-1-39789.mp3"));
        player.play();
    }//GEN-LAST:event_btnQuitMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    
}
