/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DefenseObservable.DefenseObservable;
import MilitaryVehicleEnum.MilitaryVehicle;
import javax.swing.DefaultComboBoxModel;
import DefenseObservableInterface.DefenseObservableInterface;

//import DefenseObservable.DefenseObservable;
/**
 *
 * @author Sahan Chamara
 */
public class MainControllerView extends javax.swing.JFrame {

    private static MainControllerView instance = null;
    private DefenseObservableInterface defenseObserverInterface;

    /**
     * Creates new form MainControllerView
     *
     * @param defenseObserverInterface
     */

    private MainControllerView() {
//        this.defenseObserverInterface = defenseObserverInterface;
        initComponents();
        loadComboBox();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnCollectInformation = new javax.swing.JButton();
        chkAreaClear = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        lblSoldireCount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chkSendPrivate = new javax.swing.JCheckBox();
        sliPosition = new javax.swing.JSlider();
        btnSendMain = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaMainController = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSendMainMsg = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Controller");
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Main Controller");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 0, 231, 50);

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setToolTipText("");
        jComboBox1.setName(""); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(20, 50, 160, 20);

        btnCollectInformation.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnCollectInformation.setText("Collet Information");
        btnCollectInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollectInformationActionPerformed(evt);
            }
        });
        getContentPane().add(btnCollectInformation);
        btnCollectInformation.setBounds(240, 60, 170, 20);

        chkAreaClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkAreaClear.setText("Area Clear");
        chkAreaClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAreaClearActionPerformed(evt);
            }
        });
        getContentPane().add(chkAreaClear);
        chkAreaClear.setBounds(460, 60, 90, 20);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("Position");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 170, 110, 30);

        lblSoldireCount.setBackground(new java.awt.Color(255, 255, 255));
        lblSoldireCount.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblSoldireCount.setText("Soldire Count");
        getContentPane().add(lblSoldireCount);
        lblSoldireCount.setBounds(30, 80, 110, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("Fule Count");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 110, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("Ammo Count");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 140, 110, 30);

        chkSendPrivate.setBackground(new java.awt.Color(0, 0, 0));
        chkSendPrivate.setFont(new java.awt.Font("Segoe UI Emoji", 1, 10)); // NOI18N
        chkSendPrivate.setForeground(new java.awt.Color(255, 255, 255));
        chkSendPrivate.setText("Send Private");
        chkSendPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSendPrivateActionPerformed(evt);
            }
        });
        getContentPane().add(chkSendPrivate);
        chkSendPrivate.setBounds(430, 180, 80, 10);

        sliPosition.setBackground(new java.awt.Color(0, 0, 0));
        sliPosition.setForeground(new java.awt.Color(255, 255, 255));
        sliPosition.setMajorTickSpacing(20);
        sliPosition.setMinorTickSpacing(5);
        sliPosition.setOrientation(javax.swing.JSlider.VERTICAL);
        sliPosition.setPaintLabels(true);
        sliPosition.setPaintTicks(true);
        sliPosition.setValue(0);
        sliPosition.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliPositionStateChanged(evt);
            }
        });
        getContentPane().add(sliPosition);
        sliPosition.setBounds(150, 110, 60, 170);

        btnSendMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSendMain.setText("SEND");
        btnSendMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnSendMain);
        btnSendMain.setBounds(510, 170, 70, 20);

        jScrollPane3.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        txtAreaMainController.setBackground(new java.awt.Color(0, 0, 0));
        txtAreaMainController.setColumns(20);
        txtAreaMainController.setForeground(new java.awt.Color(255, 255, 255));
        txtAreaMainController.setRows(1);
        txtAreaMainController.setTabSize(2);
        txtAreaMainController.setToolTipText("2");
        txtAreaMainController.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setViewportView(txtAreaMainController);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(410, 270, 160, 70);

        txtSendMainMsg.setBackground(new java.awt.Color(0, 0, 0));
        txtSendMainMsg.setColumns(20);
        txtSendMainMsg.setForeground(new java.awt.Color(255, 255, 255));
        txtSendMainMsg.setRows(1);
        txtSendMainMsg.setTabSize(2);
        txtSendMainMsg.setToolTipText("2");
        txtSendMainMsg.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSendMainMsg.setMaximumSize(new java.awt.Dimension(600, 400));
        txtSendMainMsg.setMinimumSize(new java.awt.Dimension(600, 400));
        txtSendMainMsg.setPreferredSize(new java.awt.Dimension(600, 400));
        jScrollPane4.setViewportView(txtSendMainMsg);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(420, 80, 160, 80);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Background Videos/main Controll 600x400.gif"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 600, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static MainControllerView getInstance() {
        if (instance == null) {
            instance = new MainControllerView();
        }
        return instance;
    }

    public void observableInterfaceReference(DefenseObservableInterface defenseObservableInterface) {
        this.defenseObserverInterface = defenseObservableInterface;
    }

    public void setComingMsg(String comingMsg) {
        txtAreaMainController.setText(comingMsg);

    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnCollectInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollectInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCollectInformationActionPerformed

    private void chkAreaClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAreaClearActionPerformed
        boolean isSelected = chkAreaClear.isSelected();
        defenseObserverInterface.setArea(isSelected);
    }//GEN-LAST:event_chkAreaClearActionPerformed

    private void chkSendPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSendPrivateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSendPrivateActionPerformed

    private void btnSendMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMainActionPerformed
        // TODO add your handling code here:
        String sendMsg = txtSendMainMsg.getText();
        defenseObserverInterface.setSendMsg(sendMsg);
    }//GEN-LAST:event_btnSendMainActionPerformed

    private void sliPositionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliPositionStateChanged

        defenseObserverInterface.setSliderPosition(sliPosition.getValue());


    }//GEN-LAST:event_sliPositionStateChanged

    private void loadComboBox() {
        jComboBox1.setModel(new DefaultComboBoxModel<>(MilitaryVehicle.values()));
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCollectInformation;
    private javax.swing.JButton btnSendMain;
    private javax.swing.JCheckBox chkAreaClear;
    private javax.swing.JCheckBox chkSendPrivate;
    private javax.swing.JComboBox<MilitaryVehicle> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblSoldireCount;
    private javax.swing.JSlider sliPosition;
    private javax.swing.JTextArea txtAreaMainController;
    private javax.swing.JTextArea txtSendMainMsg;
    // End of variables declaration//GEN-END:variables
}
