/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MilitaryVehicleEnum.MilitaryVehicle;
import SliderPositionObservableInterface.SliderPositionObservableInterface;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingUtilities;

//import DefenseObservable.DefenseObservable;
/**
 *
 * @author Sahan Chamara
 */
public class MainControllerView extends javax.swing.JFrame {

    private SliderPositionObservableInterface sliderPositionObserver;
    //private DefenseObservable defensePositionObservable;

    /**
     * Creates new form MainControllerView
     *
     * @param sliderPositionObserver
     */
    
    public MainControllerView(SliderPositionObservableInterface sliderPositionObserver) {
        this.sliderPositionObserver = sliderPositionObserver;
        initComponents();
        setLocationRelativeTo(null);
        loadComboBox();
        setVisible(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnCollectInformation = new javax.swing.JButton();
        chkAreaClear = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        lblSoldireCount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbltest = new javax.swing.JLabel();
        chkSendPrivate = new javax.swing.JCheckBox();
        sliPosition = new javax.swing.JSlider();
        btnSendMain = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaMainController = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSendMainMsg = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Controller");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jLabel1.setText("Main Controller");

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setToolTipText("");
        jComboBox1.setName(""); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnCollectInformation.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnCollectInformation.setText("Collet Information");
        btnCollectInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollectInformationActionPerformed(evt);
            }
        });

        chkAreaClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkAreaClear.setText("Area Clear");
        chkAreaClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAreaClearActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Position");

        lblSoldireCount.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblSoldireCount.setText("Soldire Count");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("Fule Count");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setText("Ammo Count");

        lbltest.setText("TEST");

        chkSendPrivate.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        chkSendPrivate.setText("Send Private");
        chkSendPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSendPrivateActionPerformed(evt);
            }
        });

        sliPosition.setMajorTickSpacing(20);
        sliPosition.setMinorTickSpacing(5);
        sliPosition.setPaintLabels(true);
        sliPosition.setPaintTicks(true);
        sliPosition.setValue(0);
        sliPosition.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliPositionStateChanged(evt);
            }
        });

        btnSendMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSendMain.setText("SEND");
        btnSendMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMainActionPerformed(evt);
            }
        });

        txtAreaMainController.setColumns(20);
        txtAreaMainController.setRows(1);
        txtAreaMainController.setTabSize(2);
        txtAreaMainController.setToolTipText("2");
        txtAreaMainController.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setViewportView(txtAreaMainController);

        txtSendMainMsg.setColumns(20);
        txtSendMainMsg.setRows(1);
        txtSendMainMsg.setTabSize(2);
        txtSendMainMsg.setToolTipText("2");
        txtSendMainMsg.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(txtSendMainMsg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnCollectInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(chkAreaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSoldireCount, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(chkSendPrivate))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnSendMain, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(lbltest, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCollectInformation)
                    .addComponent(chkAreaClear))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSoldireCount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(sliPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(chkSendPrivate)
                        .addGap(11, 11, 11)
                        .addComponent(btnSendMain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbltest))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setComingMsg(String comingMsg) {
        System.out.println("heli eken ena text eka  "+comingMsg);        

        txtAreaMainController.setText(comingMsg);     
        
        
        System.out.println("txt setarea ekata wetana text eke get text eka "+txtAreaMainController.getText());
        
       
//        txtAreaMainController1.setText(comingMsg);
//        txtAreaMainController1.repaint();
//        txtAreaMainController1.revalidate();
    }
    
    

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnCollectInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollectInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCollectInformationActionPerformed

    private void chkAreaClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAreaClearActionPerformed
        boolean isSelected = chkAreaClear.isSelected();
        sliderPositionObserver.setArea(isSelected);
    }//GEN-LAST:event_chkAreaClearActionPerformed

    private void chkSendPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSendPrivateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSendPrivateActionPerformed

    private void btnSendMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMainActionPerformed
        // TODO add your handling code here:
        String sendMsg = txtSendMainMsg.getText();
        sliderPositionObserver.setSendMsg(sendMsg);
    }//GEN-LAST:event_btnSendMainActionPerformed

    private void sliPositionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliPositionStateChanged

        sliderPositionObserver.setSliderPosition(sliPosition.getValue());


    }//GEN-LAST:event_sliPositionStateChanged

    private void loadComboBox() {
        jComboBox1.setModel(new DefaultComboBoxModel<>(MilitaryVehicle.values()));
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainControllerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainControllerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainControllerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainControllerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainControllerView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCollectInformation;
    private javax.swing.JButton btnSendMain;
    private javax.swing.JCheckBox chkAreaClear;
    private javax.swing.JCheckBox chkSendPrivate;
    private javax.swing.JComboBox<MilitaryVehicle> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblSoldireCount;
    private javax.swing.JLabel lbltest;
    private javax.swing.JSlider sliPosition;
    private javax.swing.JTextArea txtAreaMainController;
    private javax.swing.JTextArea txtSendMainMsg;
    // End of variables declaration//GEN-END:variables
}
