/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DefenseObservable.DefenseObservable;
import DefenseObserver.DefenseObserver;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Sahan Chamara
 */
public class TankView extends javax.swing.JFrame implements DefenseObserver {

    private boolean isSelected;
    private DefenseObservable observable;

    /**
     * Creates new form TankView
     * @param observable     
     */
    public TankView(DefenseObservable observable) {
        this.observable=observable;
        initComponents();
        setBottomLeftPosition();
        btnMissile.setEnabled(false);
        btnShoot1.setEnabled(false);
        btnRedar.setEnabled(false);
        btnRotateShoot.setEnabled(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRedar = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaTank = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        lblAreaTank = new javax.swing.JLabel();
        txtFiledTank = new javax.swing.JTextField();
        btnMissile = new javax.swing.JButton();
        btnSendHelicopter = new javax.swing.JButton();
        btnShoot1 = new javax.swing.JButton();
        chkPositionTank = new javax.swing.JCheckBox();
        btnRotateShoot = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        btnRedar.setBackground(new java.awt.Color(158, 122, 84));
        btnRedar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRedar.setForeground(new java.awt.Color(255, 255, 255));
        btnRedar.setText("Redar Operation");
        btnRedar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRedar);
        btnRedar.setBounds(450, 270, 122, 30);

        jSlider1.setMajorTickSpacing(20);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        getContentPane().add(jSlider1);
        jSlider1.setBounds(30, 170, 280, 40);

        txtAreaTank.setBackground(new java.awt.Color(16, 48, 73));
        txtAreaTank.setColumns(20);
        txtAreaTank.setForeground(new java.awt.Color(255, 255, 255));
        txtAreaTank.setRows(5);
        jScrollPane1.setViewportView(txtAreaTank);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 220, 250, 100);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Soldire Count");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 40, 75, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount Count");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 70, 81, 16);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(510, 40, 55, 22);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 22)); // NOI18N
        jLabel1.setText("TANK");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 0, 100, 50);
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(510, 70, 55, 22);

        lblAreaTank.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblAreaTank.setText("Area Not Cleared");
        getContentPane().add(lblAreaTank);
        lblAreaTank.setBounds(20, 40, 200, 21);

        txtFiledTank.setBackground(new java.awt.Color(121, 101, 71));
        txtFiledTank.setForeground(new java.awt.Color(255, 255, 255));
        txtFiledTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiledTankActionPerformed(evt);
            }
        });
        getContentPane().add(txtFiledTank);
        txtFiledTank.setBounds(40, 340, 230, 22);

        btnMissile.setBackground(new java.awt.Color(158, 122, 84));
        btnMissile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMissile.setForeground(new java.awt.Color(255, 255, 255));
        btnMissile.setText("Missile Operation");
        btnMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissileActionPerformed(evt);
            }
        });
        getContentPane().add(btnMissile);
        btnMissile.setBounds(450, 320, 126, 22);

        btnSendHelicopter.setBackground(new java.awt.Color(18, 37, 60));
        btnSendHelicopter.setForeground(new java.awt.Color(255, 255, 255));
        btnSendHelicopter.setText("Send");
        btnSendHelicopter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendHelicopterActionPerformed(evt);
            }
        });
        getContentPane().add(btnSendHelicopter);
        btnSendHelicopter.setBounds(280, 340, 63, 22);

        btnShoot1.setBackground(new java.awt.Color(158, 122, 84));
        btnShoot1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnShoot1.setForeground(new java.awt.Color(255, 255, 255));
        btnShoot1.setText("Shoot");
        btnShoot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShoot1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnShoot1);
        btnShoot1.setBounds(450, 170, 126, 30);

        chkPositionTank.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        chkPositionTank.setText("Position");
        chkPositionTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPositionTankActionPerformed(evt);
            }
        });
        getContentPane().add(chkPositionTank);
        chkPositionTank.setBounds(480, 140, 74, 21);

        btnRotateShoot.setBackground(new java.awt.Color(158, 122, 84));
        btnRotateShoot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRotateShoot.setForeground(new java.awt.Color(255, 255, 255));
        btnRotateShoot.setText("Rotate Shooting");
        btnRotateShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotateShootActionPerformed(evt);
            }
        });
        getContentPane().add(btnRotateShoot);
        btnRotateShoot.setBounds(450, 220, 126, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Background Videos/Tank.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 610, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void defense(int position) {
        if (position > 20 && isSelected) {
            btnShoot1.setEnabled(true);
        } else {
            btnShoot1.setEnabled(false);
        }
        if (position > 40 && isSelected) {
            btnMissile.setEnabled(true);
        } else {
            btnMissile.setEnabled(false);
        }
        if (position > 60 && isSelected) {
            btnRedar.setEnabled(true);
        } else {
            btnRedar.setEnabled(false);
        }
        if (position > 80 && isSelected) {
            btnRotateShoot.setEnabled(true);
        } else {
            btnRotateShoot.setEnabled(false);
        }
    }
    
    @Override
    public void setAreaText(boolean isSelected){
        if(isSelected){
            lblAreaTank.setText("Area Cleared");
        }else{
            lblAreaTank.setText("Area Not Cleared");
        }
    }
    
    @Override
    public void setSendMsg(String msg){
        txtAreaTank.setText(msg);
    }
    private void btnRedarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedarActionPerformed

    }//GEN-LAST:event_btnRedarActionPerformed

    private void btnMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissileActionPerformed

    }//GEN-LAST:event_btnMissileActionPerformed

    private void btnShoot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShoot1ActionPerformed

    }//GEN-LAST:event_btnShoot1ActionPerformed

    private void chkPositionTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPositionTankActionPerformed
        isSelected = chkPositionTank.isSelected();
    }//GEN-LAST:event_chkPositionTankActionPerformed

    private void btnRotateShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotateShootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRotateShootActionPerformed

    private void btnSendHelicopterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendHelicopterActionPerformed
        observable.militaryVehicleSendMsg("Tank : "+txtFiledTank.getText());        
    }//GEN-LAST:event_btnSendHelicopterActionPerformed

    private void txtFiledTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiledTankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiledTankActionPerformed

    private void setBottomLeftPosition() {
    // Get the screen dimensions
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

    // Get the height of the JFrame
    int frameHeight = this.getHeight();

    // Calculate the bottom-left position
    int x = 0; // Left edge
    int y = screenSize.height - frameHeight; // Bottom edge

    // Set the JFrame's location
    this.setLocation(x, y);
}
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMissile;
    private javax.swing.JButton btnRedar;
    private javax.swing.JButton btnRotateShoot;
    private javax.swing.JButton btnSendHelicopter;
    private javax.swing.JButton btnShoot1;
    private javax.swing.JCheckBox chkPositionTank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel lblAreaTank;
    private javax.swing.JTextArea txtAreaTank;
    private javax.swing.JTextField txtFiledTank;
    // End of variables declaration//GEN-END:variables
}
